name: Audit Test Release

on: [workflow_dispatch]

permissions: write-all

jobs:
  audit-test-release:
    runs-on: macos-12
    
    steps:
      - name: Ton Plug Tap
        run: brew tap chbinousamy/homebrew-ton

      - name: Ton Install
        run: brew install ton

      - name: Ton Audit
        run: brew audit --strict ton

      - name: Ton Test
        run: brew test ton
