name: Create release

on: [workflow_dispatch]

permissions: write-all

jobs:
  create-release:
    runs-on: [macos-12] # , ARM64]

    steps:
      - uses: actions/checkout@v3

      - name: Get latest artifacts
        run: |          
          curl -L https://github.com/ton-blockchain/ton/releases/latest/download/ton-mac-arm64.zip -o ton-mac-arm64.zip
          curl -L https://github.com/ton-blockchain/ton/releases/latest/download/ton-mac-x86-64.zip -o ton-mac-x86-64.zip
          unzip ton-mac-arm64.zip -d ton-mac-arm64
          unzip ton-mac-x86-64.zip -d ton-mac-x86-64
          mkdir -p ton-brew-arm64/bin
          mkdir -p ton-brew-arm64/lib
          mkdir -p ton-brew-x86-64/bin
          mkdir -p ton-brew-x86-64/lib
          
          mv ton-mac-arm64/* ton-brew-arm64/bin
          chmod +x ton-brew-arm64/bin/*
          mv ton-brew-arm64/bin/libtonlibjson.0.5.dylib ton-brew-arm64/lib/tonlibjson.dylib
          cd ton-brew-arm64
          tar -cvf ton-brew-arm64.tar.gz *
          
          cd ..
          mv ton-mac-x86-64/* ton-brew-x86-64/bin
          chmod +x ton-brew-x86-64/bin/*
          mv ton-brew-x86-64/bin/libtonlibjson.dylib ton-brew-x86-64/lib/tonlibjson.dylib
          rm -rf ton-brew-x86-64/bin/smartcont/
          rm -rf ton-brew-x86-64/bin/lib
          cd ton-brew-x86-64
          tar -cvf ton-brew-x86-64.tar.gz *
          
          cd ..
          mv ton-brew-arm64/ton-brew-arm64.tar.gz .
          mv ton-brew-x86-64/ton-brew-x86-64.tar.gz .
          rm -rf ton-brew-arm64 ton-brew-x86-64 ton-mac-arm64 ton-mac-arm64.zip ton-mac-x86-64 ton-mac-x86-64.zip
          
          echo ton-brew-arm64 content:
          tar -tvf ton-brew-arm64.tar.gz
          
          echo ton-brew-x86-64 content:
          tar -tvf ton-brew-x86-64.tar.gz
          
          echo get checksums
          SHA256_ARM64=$(shasum -a 256 ton-brew-arm64.tar.gz | cut -f 1 -d " ")
          SHA256_AMD64=$(shasum -a 256 ton-brew-x86-64.tar.gz | cut -f 1 -d " ")
          sed -i '' "s/sha256 \".*\" #arm64/sha256 \"$SHA256_ARM64\" #arm64/" ton.rb
          sed -i '' "s/sha256 \".*\" #amd64/sha256 \"$SHA256_AMD64\" #amd64/" ton.rb

      - name: Create release
        run: |
          LATEST_TAG=$(git ls-remote --tags https://github.com/ton-blockchain/ton/  | tail -1 | sed -n -e 's/^.*tags\///p')
          echo "LATEST_TAG $LATEST_TAG"
          git add ton.rb
          git commit -m "create release" || true
          git push          
          gh release create --notes "" $LATEST_TAG ./*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

